Repository Talend/connectors-se, pull requests merged in 2020-05, with the labels that each got.

#414 feat(TDI-44184): Improve code quality
  pom.xml
Labels: quality

#419 Dsylaiev/tdi 44181 implement azure ad auth for adls
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/datastore/AdlsGen2Connection.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/datastore/Constants.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/input/AdlsGen2Input.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/input/InputMapper.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/output/AdlsGen2Output.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/input/AvroBlobReader.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/input/BlobReader.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/input/CsvBlobReader.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/input/JsonBlobReader.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/input/ParquetBlobReader.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/AvroBlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/BlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/BlobWriterFactory.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/CsvBlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/JsonBlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/ParquetBlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsActiveDirectoryService.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/I18n.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/UIActionService.java
  azure-dls-gen2/src/main/resources/org/talend/components/adlsgen2/datastore/Messages.properties
  azure-dls-gen2/src/main/resources/org/talend/components/adlsgen2/service/Messages.properties
  azure-dls-gen2/src/test/java/org/talend/components/adlsgen2/service/AdlsGen2ServiceTestIT.java
Labels: Need review, enhancement

#412 fix(TDI-44166): Fix showing error message when blobPath starts with s…
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/input/AdlsGen2Input.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/output/AdlsGen2Output.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/AdlsGen2RuntimeException.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/runtime/output/BlobWriter.java
  azure-dls-gen2/src/main/java/org/talend/components/adlsgen2/service/AdlsGen2Service.java
  azure/azureblob/src/test/resources/excel2007/data-28.xlsx
Labels: Need review
